// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlLbmi7t1NDq8M362QjE69c9rk8d2Aa90',
    appId: '1:943233668729:web:717f43c09eae63fc3126a8',
    messagingSenderId: '943233668729',
    projectId: 'scorekeeper-e79e8',
    authDomain: 'scorekeeper-e79e8.firebaseapp.com',
    storageBucket: 'scorekeeper-e79e8.appspot.com',
    measurementId: 'G-7XVZXQFZL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHcNGwPbSe--cJrYUeRfFG1vz6rnziOr4',
    appId: '1:943233668729:android:f26aff16022b77933126a8',
    messagingSenderId: '943233668729',
    projectId: 'scorekeeper-e79e8',
    storageBucket: 'scorekeeper-e79e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE21QvAAJ9gfAcAinxZG9pmgxD6vKmMqg',
    appId: '1:943233668729:ios:aab5200df2ee8ad13126a8',
    messagingSenderId: '943233668729',
    projectId: 'scorekeeper-e79e8',
    storageBucket: 'scorekeeper-e79e8.appspot.com',
    iosClientId: '943233668729-gm5avc13ioh8u58ja2jfjasq46njrlvn.apps.googleusercontent.com',
    iosBundleId: 'com.example.scoreKeeperV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE21QvAAJ9gfAcAinxZG9pmgxD6vKmMqg',
    appId: '1:943233668729:ios:aab5200df2ee8ad13126a8',
    messagingSenderId: '943233668729',
    projectId: 'scorekeeper-e79e8',
    storageBucket: 'scorekeeper-e79e8.appspot.com',
    iosClientId: '943233668729-gm5avc13ioh8u58ja2jfjasq46njrlvn.apps.googleusercontent.com',
    iosBundleId: 'com.example.scoreKeeperV2',
  );
}
