name: Android build appbundle

on:
  push:
    branches: [ master ]

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
# on:
  # push:
    # tags:
    #   - "internal-v*.*.*" # on every version tag will build a new android artifact example: v3.1.2+6
jobs:
  build:
    name: Build Artifacts and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.0.5"

      - name: Decode android/neumodore_key.jks
        run: echo "${{ secrets.KEYSTORE_JKS_PROD }}" | base64 --decode > android/keystore.jks

      - name: Decode android/key.properties
        run: echo "${{ secrets.KEY_PROPERTIES_PROD }}" | base64 --decode > android/key.properties

      # - uses: olegtarasov/get-tag@v2 # that generate $GIT_TAG_NAME env
      #   id: tagName
      #   with:
      #     tagRegex: 'internal-v([0-9]+.[0-9]+.[0-9]+\+[0-9]+)' # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
      #     tagRegexGroup: 1 # Optional. Default is 1.

      # - name: Replace YAML version with tag version
      #   run: |
      #     sed -i 's/99.99.99+99/'$GIT_TAG_NAME'/g' pubspec.yaml|
      #     echo "Tag used version:"$GIT_TAG_NAME
      # - name: Pub Get Packages
      #   run: flutter pub get

      # - name: Build APPBUNDLE
      #   run: flutter build appbundle --release

  #     - name: Create Github Release
  #       uses: ncipollo/release-action@v1
  #       with:
  #         artifacts: "build/app/outputs/bundle/release/*.aab"
  #         token: ${{ secrets.PERSONAL_RELEASE_TOKEN }}

  #     - name: Save APPBUNDLE to Artifacts
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: APPBUNDLE
  #         path: build/app/outputs/bundle/release/app-release.aab
  # release_internal:
  #   name: Release Artifacts to internal track
  #   needs: [build]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Get APPBUNDLE from Artifacts
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: APPBUNDLE
  #     - name: Release APPBUNDLE to internal track
  #       uses: r0adkll/upload-google-play@v1
  #       with:
  #         serviceAccountJsonPlainText: ${{ secrets.GOOGLE_SERVICE_JSONKEY }}
  #         packageName: com.example.app
  #         releaseFile: app-release.aab
  #         track: internal
  #         whatsNewDirectory: distribution/whatsnew



# on:
#   push:
#     branches: [ master ]

# jobs:
#   # version:
#   #   name: Create version number
#   #   runs-on: ubuntu-latest
#   #   steps:
#   #   - uses: actions/checkout@v1
#   #   - name: Fetch all history for all tags and branches
#   #     run: |
#   #       git config remote.origin.url https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
#   #       git fetch --prune --depth=10000
#   #   - name: Install GitVersion
#   #     uses: gittools/actions/gitversion/setup@v0.9.3
#   #     with:
#   #         versionSpec: '5.2.x'
#   #   - name: Use GitVersion
#   #     id: gitversion
#   #     uses: gittools/actions/gitversion/execute@v0.9.3
#   #   - name: Create version.txt with nuGetVersion
#   #     run: echo ${{ steps.gitversion.outputs.nuGetVersion  }} > version.txt
#   #   - name: Upload version.txt
#   #     uses: actions/upload-artifact@v2
#   #     with:
#   #       name: gitversion
#   #       path: version.txt
#   build:
#     name: Build APK and Create release
#     # needs: [ version ]
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1
#     # - name: Get version.txt
#     #   uses: actions/download-artifact@v2
#     #   with:
#     #     name: gitversion
#     # - name: Create new file without newline char from version.txt
#     #   run: tr -d '\n' < version.txt > version1.txt
#     # - name: Read version
#     #   id: version
#     #   uses: juliangruber/read-file-action@v1
#     #   with:
#     #     path: version1.txt
#     # - name: Update version in YAML
#     #   run: sed -i 's/99.99.99+99/${{ steps.version.outputs.content }}+${{ github.run_number }}/g' pubspec.yaml
#     - name: Update KeyStore password in gradle properties
#       run: sed -i 's/#{KEYSTORE_PASS}#/${{ secrets.KEYSTORE_PASS }}/g' android/key.properties
#     - name: Update KeyStore key password in gradle properties
#       run: sed -i 's/#{KEYSTORE_KEY_PASS}#/${{ secrets.KEYSTORE_KEY_PASS }}/g' android/key.properties
#     - uses: actions/setup-java@v1
#       with:
#         java-version: '12.x'
#     - uses: subosito/flutter-action@v1
#       with:
#         flutter-version: '3.0.5'
#     - run: flutter pub get
#     # - run: flutter test
#     - run: flutter build apk --release --split-per-abi
#     - run: flutter build appbundle
#     # - name: Create a Release in GitHub
#     #   uses: ncipollo/release-action@v1
#     #   with:
#     #     artifacts: "build/app/outputs/apk/release/*.apk,build/app/outputs/bundle/release/app-release.aab"
#     #     token: ${{ secrets.GH_TOKEN }}
#     #     tag: ${{ steps.version.outputs.content }}
#     #     commit: ${{ github.sha }}
#   #   - name: Upload app bundle
#   #     uses: actions/upload-artifact@v2
#   #     with:
#   #       name: appbundle
#   #       path: build/app/outputs/bundle/release/app-release.aab
#   # release:
#   #   name: Release app to internal track
#   #   needs: [ build ]
#   #   runs-on: ubuntu-latest
#   #   steps:
#   #   - uses: actions/checkout@v1
#   #   - name: Get appbundle from artifacts
#   #     uses: actions/download-artifact@v2
#   #     with:
#   #       name: appbundle
#   #   - name: Release app to internal track
#   #     uses: r0adkll/upload-google-play@v1
#   #     with:
#   #       serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_ACCOUNT_KEY }}
#   #       packageName: com.fluttercicddemo
#   #       releaseFile: app-release.aab
#   #       track: internal
#   #       whatsNewDirectory: distribution/whatsnew


# # name: Flutter_Android

# # on:
#   # push:
#   #   branches: [master]
#   # pull_request:
#   #   branches: [master]

# # on: push
# # name: Release app bundle

# # jobs:
# #   build_android:
# #     runs-on: ubuntu-latest

# #     steps:
# #       - uses: actions/checkout@v3
# #       - uses: actions/setup-java@v1
# #         with:
# #           java-version: '12.x'
# #       - uses: subosito/flutter-action@v2
# #         with:
# #           flutter-version: '3.0.5'
# #           channel: 'stable'

# #       - name: Decode keystore and create jks and properties file for signing the app
# #         env:
# #           PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}
# #           KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
# #           KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
# #           KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
# #         working-directory: android
# #         run: |
# #           echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/keystore.jks
# #           echo "storeFile=keystore.jks" >> key.properties
# #           echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
# #           echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
# #           echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties

#       # - name: Create the Keystore
#       #   env:
#       #     KEYSTORE_BASE64: ${{ secrets.SCORE_KEEPER_KEYSTORE }}
#       #   run: |
#       #     # import keystore from secrets
#       #     echo $KEYSTORE_BASE64 | base64 -d > $RUNNER_TEMP/my_production.keystore

#       # - run: flutter pub get
#       # - run: flutter build appbundle --release

#       # - name: Sign Android App Bundle
#       #   run: jarsigner -keystore $RUNNER_TEMP/my_production.keystore -storepass ${{ secrets.SCORE_KEEPER_PARAPHRASE }} -keypass ${{ secrets.SCORE_KEEPER_PARAPHRASE }} -sigalg SHA256withRSA -digestalg SHA-256 -signedjar build/app/outputs/bundle/release/app-release-signed.aab build/app/outputs/bundle/release/*.aab my_production_alias

#       # - name: Publish Android Artefacts
#       #   uses: actions/upload-artifact@v1
#       #   with:
#       #     name: release-aab-signed
#       #     path: build/app/outputs/bundle/release/app-release-signed.aab

