name: Build App Bundle
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'

      - name: Download Android keystore
        # id: android_keystore
        # uses: timheuer/base64-to-file@v1.0.3
        # with:
        #   fileName: key.jks
        #   encodedString: ${{ secrets.KEYSTORE }}

        run: echo "${{ secrets.KEYSTORE }}" | base64 -di > android/key.jks

      # - name: Get Android Keystore
      #   env:
      #       ENCODED_KEYSTORE: ${{ secrets.KEYSTORE }}
      #   run: |
      #       TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
      #       mkdir "${TMP_KEYSTORE_FILE_PATH}"
      #       echo $ENCODED_KEYSTORE | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/your_keystore_file.jks

      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.SIGNING_STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.SIGNING_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.SIGNING_KEY_ALIAS }}" >> android/key.properties

      - name: Build Android App Bundle
        run: flutter build appbundle

      # Make appbundle downloadable
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: appbundle
          path: build/app/outputs/bundle/release

